version: '3'
services:
  web:
    image: lsapp
    ports:
      - "8080:8080"
    volumes:
      - app-data:/var/www/html/lsapp/data  # Mount the PVC inside the container

volumes:
  app-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/ahaggett/Public/lsappdata  # Absolute host path to the PVC